Issue 1772: SwordV1 requires xom, revert exclusion.
The error this should fix is:
```
java.lang.ClassNotFoundException: nu.xom.ParsingException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[na:na]
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[na:na]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[na:na]
        at org.purl.sword.client.Client.getServiceDocument(Client.java:314) ~[sword-common-1.1.jar:na]
        at org.purl.sword.client.Client.getServiceDocument(Client.java:244) ~[sword-common-1.1.jar:na]
        at org.tdl.vireo.model.depositor.SWORDv1Depositor.getCollections(SWORDv1Depositor.java:75) ~[classes!/:na]
        at org.tdl.vireo.controller.DepositLocationController.testConnection(DepositLocationController.java:87) ~[classes!/:na]
        at org.tdl.vireo.controller.DepositLocationController$$FastClassBySpringCGLIB$$bd8247be.invoke(<generated>) ~[classes!/:na]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.24.jar:5.3.24]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.24.jar:5.3.24]
```