Fix Test failure regarding EmailRecipientContactTest file.
The error:
```
[ERROR] Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0 s <<< FAILURE! - in org.tdl.vireo.model.EmailRecipientContactTest
[ERROR] testGetEmails  Time elapsed: 0 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Emails array does not have the correct length. ==> expected: <0> but was: <2>
	at org.tdl.vireo.model.EmailRecipientContactTest.testGetEmails(EmailRecipientContactTest.java:50)
```

This PR and commit:
- https://github.com/TexasDigitalLibrary/Vireo/pull/1923
- https://github.com/TexasDigitalLibrary/Vireo/commit/7b4a7b8c1ab66df89f42f40148291b4a88011ee7

Did not also update the unit test.

This updates the unit test to now mock `getFieldValuesByPredicateValue()` instead of mocking `getFieldValuesByPredicate()`.